# Generated by Django 4.1.7 on 2023-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blog_site',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_address',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_address',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='LinkedIn'),
        ),
    ]
