# Generated by Django 4.1.7 on 2023-03-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='caeated',
            new_name='created',
        ),
    ]
