# Generated by Django 4.1.7 on 2023-03-22 01:00

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_comment_parent_comment_comment_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True),
        ),
    ]
