# Generated by Django 4.1.7 on 2023-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_comment_votes_story_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
