# Generated by Django 4.1.7 on 2023-03-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_story_tags_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
    ]
