# Generated by Django 4.1.7 on 2023-03-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_remove_story_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
