# Generated by Django 4.1.7 on 2023-03-27 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
